[package]
name = "phira-main"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[features]
default = ["video"]
video = ["phira/video"]
chat = ["phira/chat"]
intest = ["phira/intest"]

[dependencies]
phira = { workspace = true, default-features = false }
serde_json = { workspace = true }

[build-dependencies]
winres = "0.1"