name: Download offline deb packages

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-24.04

    steps:
      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y apt-rdepends

      - name: Prepare directory
        run: |
          mkdir -p debs

      - name: Download dependencies
        run: |
          cd debs

          apt-rdepends \
            build-essential \
            dkms \
            linux-headers-generic \
          | grep -v "^ " \
          | grep -v "^<" \
          | xargs -r apt-get download

      - name: Download AIC8800 packages
        run: |
          cd debs

          wget -q https://mirror.nju.edu.cn/radxa-deb/noble-test/pool/main/a/aic8800/aic8800-firmware_*.deb || true
          wget -q https://mirror.nju.edu.cn/radxa-deb/noble-test/pool/main/a/aic8800/aic8800-pcie-dkms_*.deb || true

      - name: Show files
        run: |
          ls -lh debs

      - name: Pack
        run: |
          tar -czvf ubuntu-aic8800-offline.tar.gz debs

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-aic8800-offline
          path: ubuntu-aic8800-offline.tar.gz
